apiVersion: ENC[AES256_GCM,data:NxI=,iv:/rQO6G6y51unpWTLdZW9j1hrs3aBFHlmheVMiohC9S4=,tag:5I+AhjeCnPFCLvr/R77kbg==,type:str]
kind: ENC[AES256_GCM,data:IK+pYEbI,iv:CGCDCKe/qjBzHwIS/ymO+WTGayuJ9QtA4IJaasDLHWA=,tag:/qg894wY8DN25uK4W+Lg4A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o37XGiXDem4=,iv:rZ9OnDDSt8PW7Ey8JTk7TWpLYGfCSiqcHTPeITpLiHI=,tag:L3VhO2YQk7CKnPDqrzsFLg==,type:str]
type: ENC[AES256_GCM,data:IRu46T4y,iv:SKgzWdXyd39SxNBVeKQQDLerWQZaLRCnoKByVFqYjqA=,tag:3+A8W26tv5ZIkSt4t4WaCA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:TkPt5LRtxmc=,iv:V1U1WUauHiPK6yyReDFfsvaMGUNFEfeIuYjcTUEFUMk=,tag:zMikxskiXQUSfY8kguGbjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1j6ks4rg42ttsaw77wf3a6383kda54jk3g03zplfu8wn2vmhsk3fsm06anp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcjJJM3E5dytlenRLMUxy
            UGRpT25JSVlaTW5Id01vQnZUQnhKTk0yZVFBClh1MU90OG9KYzhnc0oyZ05MQzBG
            Q3U0QVJLS0RnREJucVozbjhwQVFHREkKLS0tIDlFdDRKS2h6Umx3NmdZLzVxU2Nr
            TnJ3a25ndGpYSzJIclpaaENsL2ZlUUEK76un1/bePrHy2KvIlGittdxroF0Nogtv
            ZiNamUt/koA0r1q/x8C1+qwNEraJoFqwm9BVUO+r2dPv5LBEUP7m8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T13:15:09Z"
    mac: ENC[AES256_GCM,data:FL4FtUtGM2GM2yZuflse5rwgjtwwscB0q7e6ZlEwz+5oBkTBEs9xwd6r/AQxclEPo700e2Z3vPnUyxiSKU/o1MITRRWkdVR0vzn55RiQe4Hab+DBxMSFtoPcFDBjezOezNz3JUI3ULfPqC1GbtzNrBjxaG0Oi0pcg7uZQUXZB1A=,iv:HHqHExCZps153nWHOpe26gsuH617csu5H0k2koBLilU=,tag:dwLMhNa/R/b6pth2q4QIkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
